name: Публикация сайта

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка репозитория
        uses: actions/checkout@v4

      - name: Настройка GitHub Pages
        uses: actions/configure-pages@v5

      - name: Подготовка артефакта
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Публикация
        id: deployment
        uses: actions/deploy-pages@v4
